version: '3.8'

services:

  rabbitmq_01:
    container_name: srvmens01
    hostname: srvmens01
    build:
      context: ./rabbitmq-01
      dockerfile: Dockerfile.yml    
    environment:
      RABBITMQ_ERLANG_COOKIE: "NCYAKUHEMPSPHHSGWFVN"
      RABBITMQ_NODENAME: "rabbit1"
    networks:
      - app-network
    ports:
     - "4369:4369"
     - "5671:5671"
     - "5672:5672"
     - "15671:15671"
     - "15672:15672"
     - "25672:25672"

  rabbitmq_02:
    container_name: srvmens02
    hostname: srvmens02
    build:
      context: ./rabbitmq-02
      dockerfile: Dockerfile.yml    
    environment:
      RABBITMQ_ERLANG_COOKIE: "NCYAKUHEMPSPHHSGWFVN"
      RABBITMQ_NODENAME: "rabbit2"
    networks:
      - app-network
    ports:
      - "15673:15672"
    depends_on:
      - rabbitmq_01

  rabbitmq_03:
    container_name: srvmens03
    hostname: srvmens03
    build:
      context: ./rabbitmq-03
      dockerfile: Dockerfile.yml
    environment:
      RABBITMQ_ERLANG_COOKIE: "NCYAKUHEMPSPHHSGWFVN"
      RABBITMQ_NODENAME: "rabbit3"
    networks:
      - app-network
    ports:
      - "15674:15672"
    depends_on:
      - rabbitmq_01

networks:
  app-network:
    driver: bridge
